# Generated by Django 4.2.4 on 2023-09-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bids_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('EL', 'electronic'), ('TO', 'toys'), ('HM', 'home'), ('FS', 'fashion'), ('OT', 'other')], default='OT', max_length=2),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
