# Generated by Django 4.2.4 on 2023-09-13 20:04

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_user_alter_auctionlisting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[auctions.models.bid_value_validator]),
        ),
    ]
