# Generated by Django 4.2.4 on 2023-09-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='Watchlist',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='is_wishlisted',
            new_name='is_watchlisted',
        ),
    ]
